name: Lighthouse Test for Mobile and Desktop View

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: lighthouse-tests
  cancel-in-progress: false

jobs:
  lighthouse-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Lighthouse CI Action
        id: lighthouse-mobile-tests
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://nennai-nyushi-navi.jp
          configPath: apps/web/lighthouserc-mobile.json
          temporaryPublicStorage: true

      - name: Build Slack Fields from Manifest
        id: build_mobile_slack_fields
        if: ${{ always() }}
        run: |
          node <<'EOF' > build_fields.js
          const fs = require('fs');

          // Read the JSON array from our environment
          const manifest = JSON.parse(process.env.MANIFEST || '[]');

          // Construct Slack fields for each item
          const fields = manifest.map(item => ({
            title: `Results for ${item.url} are`,
            value: `Performance: ${item.summary.performance??'N/A'}`.trim()
          }));
          fs.appendFileSync(process.env.GITHUB_OUTPUT, `fields=${JSON.stringify(fields)}\n`);
          EOF
          node build_fields.js
        env:
          MANIFEST: ${{ steps.lighthouse-mobile-tests.outputs.manifest }}

      - name: Send Slack Alert for Success Mobile Tests
        if: ${{ success() }}
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Lighthouse Test Passed on Mobile.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "mrkdwn_in": ["fields"] 
                "fields": ${{ steps.build_mobile_slack_fields.outputs.fields}}
              }
            ]

      - name: Send Slack Alert for Failed Mobile Tests
        if: ${{ failure() }}
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Lighthouse Test Failed on Mobile.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "mrkdwn_in": ["fields"] 
                "fields": ${{ steps.build_mobile_slack_fields.outputs.fields }}
              }
            ]
