name: Lighthouse Desktop

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build-lighthouse-Desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Installing Dependencies
        run: pnpm install

      - name: Build Web Project
        run: pnpm build:web

      - name: Lighthouse on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          cd apps/web
          pnpm install -g @lhci/cli
          lhci collect --additive --config=mobile-lighthouserc.cjs
          lhci collect --additive --config=desktop-lighthouserc.cjs
          lhci assert
          lchi upload

        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
