name: Lighthouse Desktop

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build-lighthouse-Desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Installing Dependencies
        run: pnpm install

      - name: Build Web Project
        run: pnpm build:web

      - name: Install Lighthouse CI
        run: |
          cd apps/web
          pnpm install -g @lhci/cli

      - name: Run Lighthouse Tests
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            process.chdir('apps/web');
            const lighthouseConfig = require('./lighthouserc.cjs');
            const desktopLighthouseConfig = require('./desktop-lighthouserc.cjs');
            const mobileLighthouseConfig = require('./mobile-lighthouserc.cjs');
            await exec.exec('lhci', ['healthcheck', '--fatal']);
            let assertionFailed = false;
            await exec.exec('lhci', ['collect', '--additive', '--config',desktopLighthouseConfig]);

            try {
                  await exec.exec('lhci', ['assert']);
            } catch (error) {
                  console.log('Lighthouse assertion failed, continuing...');
                  assertionFailed = true; 
            }
            await exec.getExecOutput('lhci', ['upload','--target', 'temporary-public-storage']);
            await exec.exec('rm', ['-fr', '.lighthouseci']);

            // Fail at the end if assertion failed
            if (assertionFailed) {
              console.log('Lighthouse CI assertions failed, marking the job as failed.');
              core.setFailed('Lighthouse CI assertions failed.');
            }
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
