name: Built Lighthouse Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Installing Dependencies
        run: pnpm install

      - name: Build Web Project
        run: pnpm build:web

  Lighthouse-mobile:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lighthouse on Pull Request
        run: |
          cd apps/web
          pnpm install -g @lhci/cli
          pnpm test:lighthouse:mobile -- --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
