name: Lighthouse Report

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "apps/web/**"
      - "packages/**"
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize]
jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: pnpm

      - name: Build App
        run: pnpm run build

      - name: Run Lighthouse Tests
        run: |
          pnpm install -g @lhci/cli@0.11.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v3
        with:
          name: lhci-report
          path: "./.lighthouseci"
