name: Lighthouse Test for Mobile and Desktop View

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: lighthouse-tests
  cancel-in-progress: false

jobs:
  lighthouse-mobile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Lighthouse CI Action
        id: lighthouse-mobile-tests
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://nennai-nyushi-navi.jp
            https://nennai-nyushi-navi.jp/blogs
          configPath: apps/web/lighthouserc-mobile.json
          temporaryPublicStorage: true

      - name: Send Slack Alert for Mobile Tests
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Lighthouse Test Results on Mobile.
          attachments: |
            [
              {
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "title": "Lighthouse Results URL",
                    "value": ${{ fromJson(steps.lighthouse-mobile-tests.outputs.manifest)[0].summary.performance }}
                  }
                ]
              }
            ]

  lighthouse-desktop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Lighthouse CI Action
        id: lighthouse-desktop-tests
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://nennai-nyushi-navi.jp
            https://nennai-nyushi-navi.jp/blogs
          configPath: apps/web/lighthouserc-desktop.json
          temporaryPublicStorage: true

      - name: Send Slack Alert for Desktop Tests
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Lighthouse Test Results on Desktop.
          attachments: |
            [
              {
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "Commit Message",
                    "value": "${{ github.event.head_commit.message }}"
                  },
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "title": "Lighthouse Results URL",
                    "value": ${{ fromJson(steps.lighthouse-desktop-tests.outputs.manifest)[0].summary.performance }}
                  }
                ]
              }
            ]
