name: Lighthouse Test Web App

on:
  workflow_run:
    workflows: ["Build Web App"]
    branches: [main, develop]
    types:
      - completed

permissions:
  contents: read
  actions: write

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The Web Build Action Have Passed'
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: ./build

      - name: Run Lighthouse Tests
        run: |
          pnpm test:web
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Upload Lighthouse Reports
        uses: actions/upload-artifact@v3
        with:
          name: lhci-report
          path: "./.lighthouseci"
