name: Build Web App

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize]

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env.outputs.environment }}
    steps:
      - id: get_env
        run: |
          if grep -q "refs/tags/v" <<< ${{github.ref}}  ||  grep -q "refs/heads/main" <<< ${{github.ref}}; then
            echo "environment=staging" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi
      - id: print_env
        name: Print environment
        run: echo  "Environment :- ${{ steps.get_env.outputs.environment }}"

  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Installing Dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "creating .env file"
          echo "LHCI_GITHUB_APP_TOKEN=${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN=${{ secrets.LHCI_TOKEN }}
          LHCI_SERVER_BASE_URL=${{ secrets.LHCI_SERVER_BASE_URL }}"> .env

      - name: Build Web Project
        run: pnpm run build

      - name: Lighthouse on Pull Request
        if: github.event_name == 'pull_request'
        run: |
          cd apps/web
          pnpm install -g @lhci/cli
          pnpm test:lighthouse:mobile -- --upload.target=temporary-public-storage
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}

      - name: Lighthouse on Merge/Deploy
        if: github.event_name == 'push'
        run: |
          cd apps/web
          pnpm install -g @lhci/cli
          pnpm test:lighthouse:mobile -- --upload.target=lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
