name: Build Web App

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize]

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    outputs:
      env_name: ${{ steps.get_env.outputs.environment }}
      environment: staging

  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Installing Dependencies
        run: pnpm install

      - name: Create .env file
        run: |
          echo "creating .env file"
          echo "NEXT_PUBLIC_LHCI_TOKEN=${{ secrets.LHCI_TOKEN }}
          NEXT_PUBLIC_LHCI_SERVER_BASE_URL=${{ secrets.LHCI_SERVER_BASE_URL }}"> .env

      - name: Build Web Project
        run: pnpm run build

      - name: Run Lighthouse Tests
        id: lighthouse
        run: |
          pnpm install -g @lhci/cli
          pnpm test:web:mobile
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
          NEXT_PUBLIC_LHCI_TOKEN: ${{ secrets.LHCI_TOKEN }}
          NEXT_PUBLIC_LHCI_SERVER_BASE_URL: ${{ secrets.LHCI_SERVER_BASE_URL }}
