name: Build Web App

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "apps/web/**"
      - "packages/**"
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - main
    types: [opened, synchronize]

jobs:
  build-deploy-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout Code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Installing Dependencies
        run: pnpm install

      - name: Build Web Project
        run: pnpm run build

      - name: Run Lighthouse Tests
        run: |
          pnpm install -g @lhci/cli
          pnpm test:web:mobile -- --result-path=./lhci-report.json
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

      - name: Capture Lighthouse Results
        id: lhci_results
        run: |
          # Read the Lighthouse report file and extract the score data (adjust depending on the output structure)
          PERFORMANCE_SCORE=$(jq '.categories.performance.score' lhci-report.json)
          ACCESSIBILITY_SCORE=$(jq '.categories.accessibility.score' lhci-report.json)
          BEST_PRACTICES_SCORE=$(jq '.categories.best-practices.score' lhci-report.json)
          SEO_SCORE=$(jq '.categories.seo.score' lhci-report.json)

          echo "performance_score=$PERFORMANCE_SCORE" >> $GITHUB_ENV
          echo "accessibility_score=$ACCESSIBILITY_SCORE" >> $GITHUB_ENV
          echo "best_practices_score=$BEST_PRACTICES_SCORE" >> $GITHUB_ENV
          echo "seo_score=$SEO_SCORE" >> $GITHUB_ENV

      - name: Slack Notification on TEST SUCCESS
        if: success()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }},

        with:
          text: Lighthouse Test was successful :tada:.
          attachments: |
            [
              {
                "color": "good",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "title": "Lighthouse Report URL",
                    "value": "${{ github.event.compare }}"
                  }
                ]
              }
            ]
          run: |
            echo "Lighthouse Test Passed"
            echo "Performance: Good " >> $GITHUB_STEP_SUMMARY

      - name: Slack Notification on TEST FAILURE
        if: failure()
        uses: tokorom/action-slack-incoming-webhook@main
        env:
          INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          text: Lighthouse Test Failed  :crying_cat_face:.
          attachments: |
            [
              {
                "color": "danger",
                "author_name": "${{ github.actor }}",
                "author_icon": "${{ github.event.sender.avatar_url }}",
                "fields": [
                  {
                    "title": "GitHub Actions URL",
                    "value": "${{ github.event.repository.url }}/actions/runs/${{ github.run_id }}"
                  },
                  {
                    "title": "Lighthouse Report URL",
                    "value": "${{ github.event.compare }}"
                  }
                ]
              }
            ]
          run: |
            echo "Lighthouse Test Failed"
            echo "Performance: ${{ fromJSON(steps.lighthouse.outputs.manifest)[0].summary.performance }}" >> $GITHUB_STEP_SUMMARY
